name: Build Package
on: [push, workflow_dispatch]

jobs:
  void-build:
    runs-on: ubuntu-latest
    
    container:
      image: ghcr.io/void-linux/void-glibc-full:latest
      options: --privileged

    # This sets the variables for EVERY step in the job
    env:
      ALLOW_CHROOT_AS_ROOT: "1"
      XBPS_ALLOW_RESTRICTED: "yes"
      XBPS_CHROOT_CMD: "ethereal"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prepare XBPS
        run: |
          xbps-install -Syu || xbps-install -yu xbps
          xbps-install -y git bash curl

      - name: Bootstrap xbps-src
        run: |
          # The -E flag here is the secret sauce for GitHub Actions
          ./xbps-src -E binary-bootstrap

      - name: Build Google Chrome
        run: |
          # We build using -E (Ethereal mode)
          ./xbps-src -E pkg google-chrome

      - name: Upload .xbps Artifact
        uses: actions/upload-artifact@v4
        with:
          name: google-chrome-package
          path: hostdir/binpkgs/*.xbps
